/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beecrowd.solutions;

import org.junit.Test;
import static org.junit.Assert.*;

public class BeecrowdSolverTest {

    @Test
    public void sphere1001R3() {
        BeecrowdSolver classUnderTest = new BeecrowdSolver();
        assertEquals("VOLUME = 113.097", classUnderTest.sphere1011(3));
    }

    @Test
    public void sphere1001R15() {
        BeecrowdSolver classUnderTest = new BeecrowdSolver();
        assertEquals("VOLUME = 14137.155", classUnderTest.sphere1011(15));
    }

    @Test
    public void sphere1001R1523() {
        BeecrowdSolver classUnderTest = new BeecrowdSolver();
        assertEquals("VOLUME = 14797486501.627", classUnderTest.sphere1011(1523));
    }
    
    @Test
    public void fuelSpent1017T22S67() {
        BeecrowdSolver classUnderTestFS = new BeecrowdSolver();
        assertEquals("Litros consumidos = 122.833", classUnderTestFS.fuelSpent1017(22,67));
    }
    
    @Test
    public void fuelSpent1017T2S92() {
        BeecrowdSolver classUnderTestFS = new BeecrowdSolver();
        assertEquals("Litros consumidos = 15.333", classUnderTestFS.fuelSpent1017(2,92));
    }
    
    @Test
    public void fuelSpent1017T10S85() {
        BeecrowdSolver classUnderTestFS = new BeecrowdSolver();
        assertEquals("Litros consumidos = 70.833", classUnderTestFS.fuelSpent1017(10,85));
    }
    
}
