/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beecrowd.solutions;

import org.junit.Test;
import static org.junit.Assert.*;

public class BeecrowdSolverTest {

    @Test
    public void sphere1001R3() {
        BeecrowdSolver classUnderTest = new BeecrowdSolver();
        assertEquals("VOLUME = 113.097", classUnderTest.sphere1001(3));
    }

    @Test
    public void sphere1001R15() {
        BeecrowdSolver classUnderTest = new BeecrowdSolver();
        assertEquals("VOLUME = 14137.155", classUnderTest.sphere1001(15));
    }

    @Test
    public void sphere1001R1523() {
        BeecrowdSolver classUnderTest = new BeecrowdSolver();
        assertEquals("VOLUME = 14797486501.627", classUnderTest.sphere1001(1523));
    }
}
